input_files:
  fr_file: "data/fr_reports/{pid}_fix.txt" # FR file of 1 participant. pid is extracted from argument parse when calling main.py (see the module docstring for more info)
  ia_file: "data/ia_reports/{pid}_new.txt" # IA file of the same 1 participant.  pid is extracted from argument parse when calling main.py

output:
  mapped_fr_outdir: "out" # after mapping a trial's fixations to the canonical space, a .csv of the participant's fixations over all trials will be saved to this dir.
  error_file: "errors.txt" # any errors during canonical mapping logged here. 
  output_file: "output.txt" # outputs some trial information: if any fixations were deleted bc they do not fall in a IA; counts the number of trials per IA 'format' (6 possible)

canonical_info:
  canonical_item_file: "data/canonical_item_file.csv" # the .csv containing the IA report of 1 trial of 1 participant whose info we use for canonical mapping
  # currently: canonical trial = P32LH3GPS trial 10 = 11_scientific_real





